cabify/terraform-modules

google-cloud/kubernetes/cert-manager/1_mandatory_cert_manager_namespace.yaml, google-cloud/kubernetes/cert-manager/2_mandatory_cert_manager_service_account.yaml, google-cloud/kubernetes/cert-manager/3_mandatory_custom_resource_definition_certificates.yaml, google-cloud/kubernetes/cert-manager/4_mandatory_custom_resource_definition_clusterissuers.yaml, google-cloud/kubernetes/cert-manager/5_mandatory_custom_resource_definition_issuers.yaml, google-cloud/kubernetes/cert-manager/6_mandatory_cluster_role_cert_manager.yaml, google-cloud/kubernetes/cert-manager/7_mandatory_cluster_role_binding_cert_manager.yaml, google-cloud/kubernetes/cert-manager/8_mandatory_deployment_cert_manager.yaml, google-cloud/kubernetes/cert-manager/README.md, google-cloud/kubernetes/cert-manager/cert_manager_initial_setup.tf, google-cloud/kubernetes/cert-manager/cluster_issuers.tf, google-cloud/kubernetes/cert-manager/cluster_issuers_template.yaml, google-cloud/kubernetes/cert-manager/inputs.tf, google-cloud/kubernetes/cert-manager/outputs.tf
=> Cert manager initial setup

apps/prometheus/config-map.tf, apps/prometheus/files/clusterrole.yaml, apps/prometheus/files/clusterrolebinding.yaml, apps/prometheus/files/config-map-alertrules.yaml, apps/prometheus/files/config-map-recordingrules.yaml, apps/prometheus/replication-controller.tf, apps/prometheus/serviceaccount.tf
=> Moves local-execs to k8s manifests

google-cloud/kubernetes/prometheus-stackdriver-scraper/inputs.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/replication-controller.tf
=> Adds image tag to stackdriver image

apps/prometheus/inputs.tf, apps/prometheus/storage-class.tf
=> Make storageclass variable, so we dont break production

apps/prometheus/inputs.tf, apps/prometheus/replication-controller.tf
This PR makes: 
- Livenessprobe configurable
-  Prometheus web external url configurable
=> Update some prometheus attributes

apps/prometheus/inputs.tf, apps/prometheus/replication-controller.tf
=> Make prometheis resources configurable in prometheus

google-cloud/kubernetes/prometheus-mysql-scraper/service.tf, google-cloud/sql/main.tf
Otherwise we will not scrape them if we add them to the new prometheus functions
=> Adds flag to scrape from promtheus-persistence instance

google-cloud/kubernetes/prometheus-stackdriver-scraper/README.md, google-cloud/kubernetes/prometheus-stackdriver-scraper/inputs.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/service.tf
as discussed - the scrape flag is currently hard coded, so lets make it varaible
=> Adds ability to change scrape tag

google-cloud/sql/inputs.tf
=> why u no save vim?

google-cloud/sql/inputs.tf, google-cloud/sql/main.tf
=> Removes it so we dont accidentally restart all the instances

google-cloud/kubernetes/prometheus-elasticsearch-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-mysql-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-redis-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/replication-controller.tf, google-cloud/sql/main.tf
=> Adds limits to the replication contrllers

google-cloud/sql/main.tf
=> Addms metrics to readreplicas

google-cloud/kubernetes/prometheus-mysql-scraper/replication-controller-failovers.tf
=> Renames failover replication controller resource

google-cloud/sql/main.tf
=> Moves the count to the original scraper, not the readonly replica one

google-cloud/kubernetes/prometheus-mysql-scraper/service.tf
=> maybe this will work

google-cloud/kubernetes/prometheus-mysql-scraper/service.tf
=> Forgot the placeholder

google-cloud/kubernetes/prometheus-mysql-scraper/service.tf
=> Wrong service tag for prometheus scrape

google-cloud/sql/main.tf
=> Adds maintenance windows... everywhere

google-cloud/kubernetes/prometheus-elasticsearch-scraper/inputs.tf, google-cloud/kubernetes/prometheus-elasticsearch-scraper/replication-controller.tf
=> Changes to new port

google-cloud/kubernetes/prometheus-mysql-scraper/replication-controller-failovers.tf, google-cloud/kubernetes/prometheus-mysql-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-mysql-scraper/service.tf, google-cloud/sql/inputs.tf
=> enables scraping of projects outside of cabify-production

google-cloud/kubernetes/prometheus-redis-scraper/inputs.tf, google-cloud/kubernetes/prometheus-redis-scraper/service.tf
=> adds additional labels

google-cloud/gcp/mysql/inputs.tf, google-cloud/gcp/mysql/main.tf, google-cloud/gcp/mysql/outputs.tf, google-cloud/gcp/mysql/template/metadata_shutdown_script_template.sh, google-cloud/gcp/mysql/template/metadata_startup_script_mysqlha.sh
* [Gitlab Issue](https://gitlab.otters.xyz/infrastructure/persistence/lobby/issues/159)
A terraform module to provide a MySQL HA setup over GCE.
This module will spin up three instances configured to be a single MySQL Group Replication "Cluster".
In a future step we will also add a ProxySQL instance in front of these instances.
---
cc @tnosaj
=> First commit for the google-gcp-mysql-ha module

google-cloud/kubernetes/prometheus-mysql-scraper/inputs.tf, google-cloud/kubernetes/prometheus-mysql-scraper/service.tf, google-cloud/sql/main.tf
=> adds the tier all the way down

google-cloud/sql/README.md, google-cloud/sql/databases.tf, google-cloud/sql/inputs.tf, google-cloud/sql/main.tf, google-cloud/sql/outputs.tf, google-cloud/sql/users.tf
Le NONE.
It is incompatible with terraform 0.12
Updating to terraform 0.12 syntax
---
cc tnosaj
=> Update cloudsql database module to terraform 0.12

google-cloud/kubernetes/prometheus-elasticsearch-scraper/inputs.tf, google-cloud/kubernetes/prometheus-elasticsearch-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-elasticsearch-scraper/secrets.tf, google-cloud/kubernetes/prometheus-elasticsearch-scraper/service.tf, google-cloud/kubernetes/prometheus-elasticsearch-scraper/versions.tf, google-cloud/kubernetes/prometheus-mysql-scraper/inputs.tf, google-cloud/kubernetes/prometheus-mysql-scraper/replication-controller-failovers.tf, google-cloud/kubernetes/prometheus-mysql-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-mysql-scraper/secrets.tf, google-cloud/kubernetes/prometheus-mysql-scraper/service-account.tf, google-cloud/kubernetes/prometheus-mysql-scraper/service.tf, google-cloud/kubernetes/prometheus-mysql-scraper/versions.tf, google-cloud/kubernetes/prometheus-redis-scraper/inputs.tf, google-cloud/kubernetes/prometheus-redis-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-redis-scraper/secrets.tf, google-cloud/kubernetes/prometheus-redis-scraper/service.tf, google-cloud/kubernetes/prometheus-redis-scraper/versions.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/inputs.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/replication-controller.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/secrets.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/service-account.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/service.tf, google-cloud/kubernetes/prometheus-stackdriver-scraper/versions.tf, google-cloud/sql/main.tf
=> Jt/update modules to 0.12

google-cloud/kubernetes/prometheus-mysql-scraper/inputs.tf, google-cloud/kubernetes/prometheus-mysql-scraper/service.tf, google-cloud/sql/inputs.tf, google-cloud/sql/main.tf
=> makes the scrape flag variable for mysql scraper

aws/rds/exporter_cloudwatch_enhanced_service.tf, aws/rds/exporter_cloudwatch_service.tf, aws/rds/rds_instance.tf
=> updates stuff to use right labels and also set size identical to primary

aws/rds/exporter_secrets.tf, aws/rds/exporter_sql_config.yml, aws/rds/exporter_sql_config_map.tf, aws/rds/exporter_sql_deployment.tf, aws/rds/exporter_sql_querries_users.yml, aws/rds/exporter_sql_secrets.tf, aws/rds/exporter_sql_service.tf, aws/rds/input.tf, aws/rds/mysql_user.tf
=> Setup sql-exporter to generate custom metrics based on SQL queries

aws/yace/deployment.tf, aws/yace/inputs.tf
Allow to delay metrics, really important for S3 metrics
=> YACE allow delay metrics

aws/rds/versions.tf
=> adds mysql to versions for 0.13 upgrade

aws/rds/mysql_grant.tf, aws/rds/mysql_user.tf
Start the cleanup after the SSL migration
=> Remove mysql_grant/user for replication

aws/rds/exporter_cloudwatch_deployment.tf, aws/rds/exporter_cloudwatch_enhanced_deployment.tf, aws/rds/exporter_cloudwatch_enhanced_service.tf, aws/rds/exporter_cloudwatch_service.tf, aws/rds/exporter_deployment.tf, aws/rds/exporter_secrets.tf, aws/rds/exporter_service.tf, aws/rds/exporter_sql_config_map.tf, aws/rds/exporter_sql_deployment.tf, aws/rds/exporter_sql_secrets.tf, aws/rds/exporter_sql_service.tf
We are migrating all of the K8s based exporters to production cluster. The production cluster need some labels to properly manage ownership and tiering.
I have added the labels to each k8s resource.
=> Added labels to the exporters

aws/rds/input.tf, aws/rds/rds_instance.tf
We want to untie autoupdate setting from the database tier
I have created a new parameter to allow setting `auto_minor_version_upgrade` from the module.
=> Allow to set allow_auto_update_dbs setting
